hierarchyConfigMap:
   root:
      children:
        - task5_np
        - task7_np
        - putdown_p
      domainGenerator: !!edu.umbc.cs.maple.taxi.hiergen.root.RootDomain {}
      stateMapper: !!edu.umbc.cs.maple.taxi.hiergen.root.state.HierGenRootStateMapper {}
      tf: &tf !!edu.umbc.cs.maple.hierarchy.framework.GoalFailTF
        goalPF: !!edu.umbc.cs.maple.taxi.hiergen.functions.HierGenRootCompleted {}
        failPF: !!edu.umbc.cs.maple.taxi.hiergen.functions.FailureFunction {}
      rf: !!edu.umbc.cs.maple.hierarchy.framework.GoalFailRF
        tf: *tf
        rewardDefault: 0.0
        rewardNoop: 0.0
      solver: !!edu.umbc.cs.maple.config.solver.ValueIterationMultistepConfig
        maxDelta: 0.0001
        maxIterations: 1000

   task7:
      children:
        - task5_np
        - pickup_p
      domainGenerator: !!edu.umbc.cs.maple.taxi.hiergen.task7.Task7Domain {}
      stateMapper: !!edu.umbc.cs.maple.taxi.hiergen.task7.state.Task7StateMapper {}
      tf: &tf !!edu.umbc.cs.maple.hierarchy.framework.GoalFailTF
        goalPF: !!edu.umbc.cs.maple.taxi.hiergen.functions.HierGenTask7Completed {}
        failPF: !!edu.umbc.cs.maple.taxi.hiergen.functions.FailureFunction {}
      rf: !!edu.umbc.cs.maple.hierarchy.framework.GoalFailRF
        tf: *tf
        rewardDefault: 0.0
        rewardNoop: 0.0
      solver: !!edu.umbc.cs.maple.config.solver.ValueIterationMultistepConfig
        maxDelta: 0.0001
        maxIterations: 1000

   task5:
      children:
        - north_p
        - south_p
        - east_p
        - west_p
      domainGenerator: !!edu.umbc.cs.maple.taxi.hiergen.task5.Task5Domain {}
      stateMapper: !!edu.umbc.cs.maple.taxi.hiergen.task5.state.Task5StateMapper {}
      tf: &tf !!edu.umbc.cs.maple.hierarchy.framework.GoalFailTF
        goalPF: !!edu.umbc.cs.maple.taxi.hiergen.functions.HierGenTask5Completed {}
        failPF: !!edu.umbc.cs.maple.taxi.hiergen.functions.FailureFunction {}
      rf: !!edu.umbc.cs.maple.hierarchy.framework.GoalFailRF
        tf: *tf
        rewardDefault: 0.0
        rewardNoop: 0.0
      solver: !!edu.umbc.cs.maple.config.solver.ValueIterationMultistepConfig
        maxDelta: 0.0001
        maxIterations: 1000