domain: !!config.taxi.TaxiConfig
  state: classic
  correct_move: 1.0
  fickle: 0.00

agents:
  - rmaxqExpert
  - rmaxqHierGen
  - palmExpert
  - palmExpertWithNavGiven
  - palmHierGen
  - kappaExpert
  - kappaHierGen
  - qLearning

seed: 2320942930
episodes: 200
max_steps: 1000
trials: 1
gamma: 0.99

identifier_independent: false
planning:
  rollouts: 1000

rmax:
  vmax: 1.0
  threshold: 3
  max_delta: 0.0001
  max_delta_rmaxq: 0.0001
  max_iterations_in_model: 1000
  use_multitime_model: true
  wait_for_children: true


output:
  csv:
    enabled: true
    output: results/classic.csv

  chart:
    enabled: true

    width: 500
    height: 300
    columns: 2
    max_height: 900
    trial_mode: MOST_RECENT_AND_AVERAGE

    metrics:
      - STEPS_PER_EPISODE
      - CUMULATIVE_REWARD_PER_STEP
      - CUMULATIVE_REWARD_PER_EPISODE

  visualizer:
    enabled: false
    episodes: true
    width: 5
    height: 5
    

