domain: !!config.taxi.TaxiConfig
  state: mehta-zigzag-1
  correct_move: 1.0
  fickle: 0.04

agents:
  - palmExpert
  - palmHierGen
  - expStepsExpert
  - expStepsHierGen
# - rmaxq

episodes: 100
max_steps: 2000
trials: 5
gamma: 0.99

seed: 7543221

planning:
  rollouts: 1000

rmax:
  vmax: 1.0
  threshold: 5
  max_delta: 0.0001
  max_delta_rmaxq: 0.0001
  max_iterations_in_model: 1000
  use_multitime_model: true
  wait_for_children: true

output:
  csv:
    enabled: true
    output: results/noah-test.csv

  chart:
    enabled: true

    width: 300
    height: 200
    columns: 2
    max_height: 900
    trial_mode: MOST_RECENT_AND_AVERAGE

    metrics:
      - STEPS_PER_EPISODE
      - CUMULATIVE_REWARD_PER_STEP
      - CUMULATIVE_REWARD_PER_EPISODE

  visualizer:
    enabled: true
    episodes: true
    width: 5
    height: 5
    
