domain: !!edu.umbc.cs.maple.config.taxi.TaxiConfig
  state: classic-2passengers
  correct_move: 1.0
  fickle: 0.04

agents:
#    - rmaxqExpert
  #  - rmaxqHierGen
    - palmExpert
    - palmExpertWithNavGiven
    - palmHierGen
    - kappaExpert
    - kappaHierGen
#    - qLearning
episodes: 250
max_steps: 4000
trials: 1
gamma: 0.99

seed: 7543221


identifier_independent: false
planning:
  rollouts: 1000

rmax:
  vmax: 10.0
  threshold: 10
  max_delta: 0.0001
  max_delta_rmaxq: 0.0001
  max_iterations_in_model: 1000
  use_multitime_model: true
  use_model_sharing: true


output:
  csv:
    enabled: true
    output: results/pex-classic-2-fickle.csv

  chart:
    enabled: true

    width: 500
    height: 230
    columns: 2
    max_height: 693
    trial_mode: MOST_RECENT_AND_AVERAGE

    metrics:
      - STEPS_PER_EPISODE
      - CUMULATIVE_REWARD_PER_STEP
      - CUMULATIVE_REWARD_PER_EPISODE

  visualizer:
    enabled: false
    episodes: true
    width: 5
    height: 5
    
