domain: !!edu.umbc.cs.maple.config.taxi.TaxiConfig
  state: classic-2passengers
  correct_move: 0.90
  fickle: 0.00

agents:
#  - palmExpert
  - kappaExpert
#  - palmHierGen
#  - kappaHierGen

seed: 765432
episodes: 100
max_steps: 1000
trials: 1
gamma: 0.95

identifier_independent: false
planning:
  rollouts: 1000

rmax:
  vmax: 10.0
  threshold: 5
  max_delta: 0.0000001
  max_delta_rmaxq: 0.0000001
  max_iterations_in_model: 1000
  use_multitime_model: true
  wait_for_children: true
  use_model_sharing: false


output:
  csv:
    enabled: true
    output: results/classic.csv

  chart:
    enabled: true

    width: 500
    height: 230
    columns: 2
    max_height: 693
    trial_mode: MOST_RECENT_AND_AVERAGE

    metrics:
      - STEPS_PER_EPISODE
      - CUMULATIVE_REWARD_PER_STEP
      - CUMULATIVE_REWARD_PER_EPISODE

  visualizer:
    enabled: false
    episodes: true
    width: 5
    height: 5
    

