domain: !!edu.umbc.cs.maple.config.taxi.TaxiConfig
  state: classic-2passengers
  correct_move: 1.0
  fickle: 0.04
  
seed: 89424

agents:
#  - palmExpert
  - palmHierGen

episodes: 100
max_steps: 2000
trials: 1
gamma: 0.99

identifier_independent: false
planning:
  rollouts: 1000

rmax:
  vmax: 10.0
  threshold: 10
  max_delta: 0.0001
  max_delta_rmaxq: 0.0001
  max_iterations_in_model: 1000
  use_multitime_model: true
  wait_for_children: true
  use_model_sharing: false

output:
  csv:
    enabled: true
    output: results/taxi-test-2.csv

  chart:
    enabled: true

    width: 500
    height: 300
    columns: 2
    max_height: 900
    trial_mode: MOST_RECENT_AND_AVERAGE

    metrics:
      - STEPS_PER_EPISODE
      - CUMULATIVE_REWARD_PER_STEP
      - CUMULATIVE_REWARD_PER_EPISODE

  visualizer:
    enabled: true
    episodes: true
    width: 5
    height: 5
    
