name: expert
hierarchyConfigMap:
   root:
      children:
        - get_np
        - put_np
      domainGenerator: !!edu.umbc.cs.maple.liftCopter.hierarchies.expert.tasks.root.LCRootDomain {}
      stateMapper: !!edu.umbc.cs.maple.liftCopter.hierarchies.expert.tasks.root.state.RootStateMapper {}
      tf: &tf !!edu.umbc.cs.maple.hierarchy.framework.GoalFailTF
        goalPF: !!edu.umbc.cs.maple.liftCopter.hierarchies.functions.RootCompletedPF {}
        failPF: !!edu.umbc.cs.maple.liftCopter.hierarchies.functions.RootFailurePF {}
      rf: !!edu.umbc.cs.maple.hierarchy.framework.GoalFailRF
        tf: *tf
        rewardDefault: 0.0
        rewardNoop: 0.0
      solver: !!edu.umbc.cs.maple.config.solver.ValueIterationMultistepConfig
        maxDelta: 0.0001
        maxIterations: 1000

   get:
      children:
        - nav_np
        - pickup_p
      domainGenerator: !!edu.umbc.cs.maple.liftCopter.hierarchies.expert.tasks.get.LCGetDomain {}
      stateMapper: !!edu.umbc.cs.maple.liftCopter.hierarchies.expert.tasks.get.state.GetStateMapper {}
      tf: &tf !!edu.umbc.cs.maple.hierarchy.framework.GoalFailTF
        goalPF: !!edu.umbc.cs.maple.liftCopter.hierarchies.functions.GetCompletedPF {}
        failPF: !!edu.umbc.cs.maple.liftCopter.hierarchies.functions.GetFailurePF {}
      rf: !!edu.umbc.cs.maple.hierarchy.framework.GoalFailRF
        tf: *tf
        rewardDefault: 0.0
        rewardNoop: 0.0
      solver: !!edu.umbc.cs.maple.config.solver.ValueIterationMultistepConfig
        maxDelta: 0.0001
        maxIterations: 1000

   put:
      children:
        - nav_np
        - putdown_p
      domainGenerator: !!edu.umbc.cs.maple.liftCopter.hierarchies.expert.tasks.put.LCPutDomain {}
      stateMapper: !!edu.umbc.cs.maple.liftCopter.hierarchies.expert.tasks.put.state.PutStateMapper {}
      tf: &tf !!edu.umbc.cs.maple.hierarchy.framework.GoalFailTF
        goalPF: !!edu.umbc.cs.maple.liftCopter.hierarchies.functions.PutCompletedPF {}
        failPF: !!edu.umbc.cs.maple.liftCopter.hierarchies.functions.PutFailurePF {}

      rf: !!edu.umbc.cs.maple.hierarchy.framework.GoalFailRF
        tf: *tf
        rewardDefault: 0.0
        rewardNoop: 0.0
      solver: !!edu.umbc.cs.maple.config.solver.ValueIterationMultistepConfig
        maxDelta: 0.0001
        maxIterations: 1000

   nav:
      children:
        - thrust|0.02|.5_p
        - thrust|0.02|1.5_p
        - thrust|0.02|0.0_p
        - thrust|0.02|1_p
        - noop_p
      domainGenerator: !!edu.umbc.cs.maple.liftCopter.hierarchies.expert.tasks.nav.LCNavDomain {}
      stateMapper: !!edu.umbc.cs.maple.liftCopter.hierarchies.expert.tasks.nav.state.NavStateMapper {}
      tf: &tf !!edu.umbc.cs.maple.hierarchy.framework.GoalFailTF
        goalPF: !!edu.umbc.cs.maple.liftCopter.hierarchies.functions.NavCompletedPF {}
        failPF: !!edu.umbc.cs.maple.liftCopter.hierarchies.functions.NavFailurePF {}
      rf: !!edu.umbc.cs.maple.hierarchy.framework.GoalFailRF
        tf: *tf
        rewardDefault: 0.0
        rewardNoop: 0.0
      solver: !!edu.umbc.cs.maple.config.solver.SarsaLambdaConfig
        lambda: 0.5
        learningRate: 0.02
        TCC: !!edu.umbc.cs.maple.config.TileCoding.LCTileCodingConfig
          res: 5