domain: !!edu.umbc.cs.maple.config.cleanup.CleanupConfig
    state: threeRooms
    num_blocks: 2
    minX: 0
    minY: 0
    maxX: 10
    maxY: 10
    rewardGoal: 1.0
    rewardBase: 0.0
    rewardNoop: 0.0
    rewardPull: 0.0
    goalParams:
      - [block0, room1]

agents:
  palm: {cleanup-expert}

seed: 32552
episodes: 100
max_steps: 1000
trials: 1
gamma: 0.95

identifier_independent: false
planning:
  rollouts: 10000

rmax:
  vmax: 1.0
  threshold: 5
  max_delta: 0.0001
  max_iterations_in_model: 1000
  use_multitime_model: true
  wait_for_children: true

output:
  csv:
    enabled: true
    output: results/palm-cleanup-3rooms2blocks.csv

  chart:
    enabled: true

    width: 300
    height: 300
    columns: 2
    max_height: 900
    trial_mode: MOST_RECENT_AND_AVERAGE

    metrics:
      - STEPS_PER_EPISODE
      - CUMULATIVE_REWARD_PER_STEP
      - CUMULATIVE_REWARD_PER_EPISODE

  visualizer:
    enabled: true
    episodes: true
    width: 5
    height: 5
